apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omar
  namespace: apache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile  # Make sure the storage class matches what you're using
